version: '3.8'

services:
  vault_primary:
    image: vault:latest
    container_name: vault_primary
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: "vault server -dev -dev-root-token-id=root -dev-listen-address=0.0.0.0:8200"
  
  vault_replica:
    image: vault:latest
    container_name: vault_replica
    ports:
      - "8201:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: "vault server -dev -dev-root-token-id=root -dev-listen-address=0.0.0.0:8200"

  courier:
    image: ncode/courier:dev
    container_name: courier
    depends_on:
      - vault_primary
      - vault_replica
    command: /bin/sh -c "while sleep 1000; do :; done"

